# -- Docker Compose Example --
# sane defaults implemented
services:
    frontend:
        # use the docker file provided
        build: 
            context: .
            dockerfile: ./frontend/Dockerfile
        # name of container in docker daemon
        container_name: scrapbook-frontend
        # expose port
        ports:
            # port used by vite
            - 80:80
        # use internal network
        networks:
            - internal

    backend:
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        container_name: scrapbook-backend
        ports:
            - 3000:3000
        networks:
            - internal


networks:
    internal:
        driver: bridge